service: avshare2-api
deprecationNotificationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-1
  memorySize: 512
  timeout: 30
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::jp-live-bruin-iwai-audio-video/*
  deploymentBucket:
    name: jp-live-bruin-iwai-serverlessdeploymentbucket
    blockPublicAccess: true
  tracing:
    apiGateway: true
    lambda: true
  logRetentionInDays: 14
  endpointType: regional
  apiGateway:
    apiKeys:
      - ${self:provider.stage}-myFirstKey

plugins:
  - serverless-esbuild
  - serverless-plugin-lambda-insights

custom:
  lambdaInsights:
    defaultLambdaInsights: true
    lambdaInsightsVersion: 32

functions:
  getContentsList:
    handler: app/handler.getContentsList
    events:
      - http:
          path: contents/{prefix}
          method: get
          private: true
          cors: true
          request:
            parameters:
              paths:
                prefix: true
    environment:
      BUCKET_NAME: jp-live-bruin-iwai-audio-video
