service: avshare2-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::jp-live-bruin-iwai-audio-video/*
  deploymentBucket:
    blockPublicAccess: true
  tracing:
    apiGateway: true
    lambda: true
  logRetentionInDays: 14
plugins:
  - serverless-layers
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-pseudo-parameters
functions:
  hello:
    handler: handler.hello
